# docker-compose.yml
services:
  api:
    image: zebius-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zebius-api-${SUFFIX}
    network_mode: host
    env_file:
      - .env
    depends_on:
      - dragonfly
    volumes:
      - .:/app
    restart: unless-stopped

  # 기존 redis 서비스 정의 부분 (↓ 이 부분을 **모두 삭제**하고 ↓)
  # redis:
  #   image: redis:latest
  #   container_name: zebius-redis
  #   network_mode: host # 또는 설정한 네트워크
  #   command: ["redis-server", "/usr/local/etc/redis/redis.conf"] # 또는 다른 명령어
  #   volumes:
  #     - redis-data:/data
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf # 또는 다른 설정 파일
  #   ulimits:
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  #   restart: unless-stopped

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    volumes:
      - dragonfly-data:/data
    network_mode: host
    restart: unless-stopped

  flusher:
    image: flusher
    build:
      context: ./flusher
    container_name: flusher-${SUFFIX}
    volumes:
      - ./flusher/logs:/logs
    env_file:
      - .env
    depends_on:
      - dragonfly
    network_mode: host

volumes:
  dragonfly-data:
