services:
  api:
    image: zebius-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zebius-api-${SUFFIX}
    network_mode: host
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: zebius-mongo
    network_mode: host
    command: ["mongod", "--config", "/etc/mongod.conf"]
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: zebius-redis
    network_mode: host
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:
