services:
  app:
    build: .
    container_name: zebius-app
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo
    container_name: zebius-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis
    container_name: zebius-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo-data:
