services:
  api:
    image: zebius-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zebius-api-${SUFFIX}
    network_mode: host
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: zebius-redis
    network_mode: host
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    restart: unless-stopped

  flusher:
    image: flusher
    build:
      context: ./flusher
    container_name: flusher-${SUFFIX}
    volumes:
      - ./flusher/logs:/logs
    env_file:
      - .env
    depends_on:
      - redis
    network_mode: host

volumes:
  redis-data:
